### ISSUE TITLE
[Bug]: GGR329 Course name and description display error

### ISSUE THREAD

**Issue by math-lee** [magellan-developper/test-round-1#10]
### Describe the bug

The description and title is incorrect

### How To Reproduce

add ggr329 to courses, see that the title is wrong. 

### Expected behavior

Should display "The Global Food System"

### What device were you using when you encountered the error?

Macbook Air

### What browser were you using when you encountered the error?

Chrome

### What operating system were you using?

Mac OS

**Comment by Leo6Leo** [comment]
![CleanShot 2024-10-20 at 21 49 12@2x](https://github.com/user-attachments/assets/7785e05a-3467-4f8e-aefa-4ba69d9f7dd1)
![CleanShot 2024-10-20 at 21 49 53@2x](https://github.com/user-attachments/assets/9fc8bc8c-ebc0-4657-83c6-eaac381655da)

The issue has been addressed. Thanks for reporting! @math-lee
