### ISSUE TITLE
Minor/Certificate Checker

### ISSUE THREAD

**Issue by MEGmax** [magellan-developper/test-round-1#8]
### Is your feature request related to a problem? Please describe.

It is difficult to check manually if you have enough courses to get a minor or a certificate and still meet the requirements to graduate. This is because of the 2 course rule, where you can only count a course towards 2 of three things: 

1. ECE graduation requirements
2. A minor (one)
3. A certificate (one)

Outlining this on pen and paper, making sure you don't "triple dip" courses is tedious.

### Describe the solution you'd like

Perhaps a tab in the upper header titled "Minor/Certification Eligibility" or even something built into the profile evaluation feature. You could implement it so it only shows which minors/certificates you qualify for or display all of the minors/certificates and show how many courses you could count toward that designation. 

### Additional Information

**Link to "double dip" restriction:**
https://undergrad.engineering.utoronto.ca/academics-registration/enrolment-registration/taking-extra-courses/#:~:text=While%20any%20course%20can%20be%20used%20to%20fulfill%20two%20separate%20program%20requirements%20(e.g.%2C%20undergraduate%20degree%20elective%20and%20certificate%20program)

**Comment by Leo6Leo** [comment]
@MEGmax  Thanks for the suggestion Mattew! This feature has been developed, and it is in the testing stage. It is called "Minor Booster". Check out the demo video [here](https://youtu.be/ntZ2fxYjsD4?t=68)!

**Comment by MEGmax** [comment]
Thats so cool! Do you need any help developing the feature or testing? I'd love to contribute.
